const apostas = [
    {
        "nome": "Fabio Cesar de Carvalho",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "0",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "2",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Marcelo José de Melo",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "1",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Isabel Silva de Mello ",
        "Jogo-A-1": "1",
        "Jogo-B-1": "2",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "4",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "0",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "4",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Robert Koziolek",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "1",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Morgana Beatriz de Faria Koziolek",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "6",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "0",
        "Jogo-B-7": "3",
        "Jogo-A-8": "1",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Ryszard Koziolek ",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "5",
        "Jogo-B-2": "1",
        "Jogo-A-3": "0",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Rodrigo Alves Ramalho ",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Paulo Cesar de Carvalho",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "0",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "1",
        "Jogo-A-5": "0",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "3",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Sebastião Ilto de Andrade Júnior ",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "0",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "0",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Eleandra Maria Costa Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Larissa Maria Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "1",
        "Jogo-B-2": "1",
        "Jogo-A-3": "4",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "4",
        "Jogo-A-8": "2",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Tiago Rezende",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "0",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Any Karoline Castro",
        "Jogo-A-1": "2",
        "Jogo-B-1": "2",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "0",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Pedro Cesar Evangelista Chagas",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "0",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "0",
        "Jogo-A-8": "0",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Antônio João da Silva Goulart júnior Goulart",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "3",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Renato Alves Ramalho",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "1",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "0",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "0",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Ricardo Renzi",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "3",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "0",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Maria Suely de Andrade",
        "Jogo-A-1": "0",
        "Jogo-B-1": "1",
        "Jogo-A-2": "4",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Walter Luiz Schmidt Modesto ",
        "Jogo-A-1": "2",
        "Jogo-B-1": "2",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "0",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "3",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Vania Elizabeth de Oliveira Modesto ",
        "Jogo-A-1": "1",
        "Jogo-B-1": "2",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "2",
        "Jogo-A-7": "0",
        "Jogo-B-7": "1",
        "Jogo-A-8": "3",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Vania Martins da Silva",
        "Jogo-A-1": "3",
        "Jogo-B-1": "2",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "4",
        "Jogo-B-3": "2",
        "Jogo-A-4": "1",
        "Jogo-B-4": "2",
        "Jogo-A-5": "2",
        "Jogo-B-5": "3",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "1",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Angelita Vilela Dorta",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "0",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Alexandre Ricardo ",
        "Jogo-A-1": "1",
        "Jogo-B-1": "2",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "2",
        "Jogo-A-5": "0",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "3",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Tales Henrique Carvalho",
        "Jogo-A-1": "3",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "3",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "4",
        "Jogo-A-8": "3",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Kleiton D'Angelo",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "2",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Carla Costa Ferreira ",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "0",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Paulo Eduardo Pereira Magalhães",
        "Jogo-A-1": "0",
        "Jogo-B-1": "0",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "1",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "2",
        "Jogo-A-6": "1",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "1",
        "Jogo-A-8": "0",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Guilherme Augusto Gomes de Almeida ",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "4",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "2",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Aurelio Lino de Almeida ",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "1",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "0",
        "Jogo-A-6": "1",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Leandro Mendes de Faria",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "2",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Priscilla Mesquita",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "0",
        "Jogo-B-4": "1",
        "Jogo-A-5": "0",
        "Jogo-B-5": "2",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Marcos Cezar de Carvalho",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "0",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "2",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "2",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Carlos Eduardo Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Carlos Roberto de Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "2",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "3",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Raquel Cristina de Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "3",
        "Jogo-A-8": "1",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Júlio César de Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "2",
        "Jogo-A-2": "5",
        "Jogo-B-2": "1",
        "Jogo-A-3": "3",
        "Jogo-B-3": "2",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "3",
        "Jogo-B-5": "1",
        "Jogo-A-6": "4",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Adriana Estela Faria de Guimbard",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "2",
        "Jogo-A-4": "1",
        "Jogo-B-4": "2",
        "Jogo-A-5": "2",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "2",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Marcelo Duarte Campos",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Lourdes Marisa Figueiredo Lemes",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "1",
        "Jogo-B-2": "2",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Luís Guimbard",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "2",
        "Jogo-A-4": "1",
        "Jogo-B-4": "2",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Diego Orsi Gonçalves",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "0",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "0"
    },
    {
        "nome": "Willian Augusto Gomes",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "0",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Michelle Swerts",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "0",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "0",
        "Jogo-B-7": "11",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Benedita Mendes Dorta",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "0",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "2",
        "Jogo-B-7": "1",
        "Jogo-A-8": "1",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Marcos Constantino Korczak da Rosa",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "3",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Benedita Mendes Dorta",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "1",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "2",
        "Jogo-B-7": "1",
        "Jogo-A-8": "1",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Marisa Amélia Modesto Vieira",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "2",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "3",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Adriene Vilela Santos",
        "Jogo-A-1": "1",
        "Jogo-B-1": "2",
        "Jogo-A-2": "1",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Carlos Henrique Freitas de Souza Júnior",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "0",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "1",
        "Jogo-A-7": "1",
        "Jogo-B-7": "4",
        "Jogo-A-8": "3",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Nádya Lino Faustino",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "0",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Guido Gabriel Guimbard",
        "Jogo-A-1": "3",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "3",
        "Jogo-A-3": "1",
        "Jogo-B-3": "2",
        "Jogo-A-4": "2",
        "Jogo-B-4": "2",
        "Jogo-A-5": "3",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Claudia Fernanda Bueno Garcia",
        "Jogo-A-1": "2",
        "Jogo-B-1": "0",
        "Jogo-A-2": "1",
        "Jogo-B-2": "0",
        "Jogo-A-3": "1",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "2",
        "Jogo-B-6": "1",
        "Jogo-A-7": "0",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Ana Paula Coutinho Moraes",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "2",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "1",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Ivan Figueiredo Lemes",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "1",
        "Jogo-A-3": "1",
        "Jogo-B-3": "0",
        "Jogo-A-4": "4",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "3",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Marco Antônio Gomes de Carvalho",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "1",
        "Jogo-A-5": "1",
        "Jogo-B-5": "0",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "2",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Glaucir Antunes Modesto",
        "Jogo-A-1": "1",
        "Jogo-B-1": "1",
        "Jogo-A-2": "3",
        "Jogo-B-2": "1",
        "Jogo-A-3": "3",
        "Jogo-B-3": "0",
        "Jogo-A-4": "3",
        "Jogo-B-4": "1",
        "Jogo-A-5": "2",
        "Jogo-B-5": "1",
        "Jogo-A-6": "1",
        "Jogo-B-6": "1",
        "Jogo-A-7": "2",
        "Jogo-B-7": "3",
        "Jogo-A-8": "2",
        "Jogo-B-8": "2"
    },
    {
        "nome": "Renato Ferreira Ayres",
        "Jogo-A-1": "1",
        "Jogo-B-1": "0",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "1",
        "Jogo-B-4": "0",
        "Jogo-A-5": "0",
        "Jogo-B-5": "1",
        "Jogo-A-6": "3",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "3",
        "Jogo-A-8": "1",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Luis Phellyppe Turci Navalon Rodrigues",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "2",
        "Jogo-B-2": "0",
        "Jogo-A-3": "2",
        "Jogo-B-3": "1",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "0",
        "Jogo-B-5": "1",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "0",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "1"
    },
    {
        "nome": "Lucas Anastasi Fiorani",
        "Jogo-A-1": "2",
        "Jogo-B-1": "1",
        "Jogo-A-2": "0",
        "Jogo-B-2": "1",
        "Jogo-A-3": "2",
        "Jogo-B-3": "0",
        "Jogo-A-4": "2",
        "Jogo-B-4": "0",
        "Jogo-A-5": "1",
        "Jogo-B-5": "3",
        "Jogo-A-6": "2",
        "Jogo-B-6": "0",
        "Jogo-A-7": "1",
        "Jogo-B-7": "2",
        "Jogo-A-8": "2",
        "Jogo-B-8": "0"
    }
]